### ISSUE TITLE
incremental Makefile

### ISSUE THREAD

**Issue by maxsnew** [maxsnew/cubical-categorical-logic#89]
current Makefile is not incremental at all, it recompiles everything every time. I tried it out and the one from `agda-categories` does not have this issue so we should copy it: https://github.com/agda/agda-categories/blob/master/Makefile

**Comment by hejohns** [comment]
Reading the zulip message made me think you were going to propose changing the Makefile to look for agdai files under ./_build/.
Double checking that you do in fact mean scripting (well, copying the script from agda-cateogories) a top level "import everything" agda file, and just invoking Make to check that one file, letting agda handle the caching.

Also, the current Makefile only checks ./Cubical/.
Is this something we still want to do?

Otherwise I can do this right now.

**Comment by maxsnew** [comment]
I think we should just adapt the approach taken in their script. And it should build everything not just Cubical

**Comment by maxsnew** [comment]
implemented by https://github.com/maxsnew/cubical-categorical-logic/pull/90
